---
# Установка Telegraf
- name:  Install Telegraf
  yum: name=telegraf state=latest

- name: Copy telegraf.conf on server
  copy: src={{ "telegraf.conf" }}  dest={{ destin_folder_telegraf }} mode=0555

- name: Start Telegraf
  service: name=telegraf state=started enabled=yes